---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Set up the basic requirements and settings of all Ubuntu servers

- import_tasks: prereqs.yml
- import_tasks: zsh.yml
- import_tasks: ntp.yml
- import_tasks: thefuck.yml
- import_tasks: systemd.yml
