---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Set up the basic requirements and settings of all Ubuntu servers

- import_tasks: prereqs.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: zsh.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: ntp.yml
  when: ansible_distribution == 'Ubuntu'
- import_tasks: thefuck.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version < "24.04" #TODO fix this when the package is fixed
- import_tasks: systemd.yml
  when: ansible_distribution == 'Ubuntu'
