---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage NTP configuration

- name: Install NTP
  apt:
    name: ntp
    state: present

- name: Set localtime symlink to UCT
  set_fact:
    tzsymlink: "UCT"

- name: Set the correct time zone for localtime
  file:
    path: /etc/localtime
    state: link
    src: "/usr/share/zoneinfo/UCT"
    force: yes

- name: Verify NTP is enabled and running
  service:
    name: ntp
    state: started
    enabled: yes
