---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage NTP configuration

- name: Install NTP
  apt:
    name: ntp
    state: present

- name: (Ubuntu 16.04) Set localtime symlink to UTC
  set_fact:
    tzsymlink: "UTC"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"

- name: (Ubuntu 18.04+) Set localtime symlink to UTC
  set_fact:
    tzsymlink: "UCT"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= "18.04"

- name: Set the correct time zone for localtime
  file:
    path: /etc/localtime
    state: link
    src: "/usr/share/zoneinfo/{{ tzsymlink }}"
    force: yes

- name: Configure timezone to UTC
  copy:
    src: UTCtimezone
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify:
    - ubuntu reconfigure timezone

- name: Verify NTP is enabled and running
  service:
    name: ntp
    state: started
    enabled: yes
