---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage NTP configuration

- name: Install NTP
  apt:
    name: ntp
    state: present
  when: ansible_distribution_version < "24.04"

- name: Set localtime symlink to correct TZ
  set_fact:
    tzsymlink: "{{ ubuntu_base.tzsymlink }}"

- name: Set the correct time zone for localtime
  file:
    path: /etc/localtime
    state: link
    src: "{{ ubuntu_base.localtime }}"
    force: yes

- name: Verify NTP is enabled and running
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution_version < "24.04"
