---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage packages that should be added or removed
- name: Refresh apt cache
  apt:
    update_cache: yes

- name: Remove unused packages
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - landscape-client-ui
      - landscape-client-ui-install
      - landscape-client
      - landscape-common
      - update-motd
      - cloud-init

- name: Add the usual packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bmon
      - htop
      - vim
      - curl
      - gnupg2
      - atop
      - git
      - molly-guard
      - python-pip
      - python-dev
      - python3-pip
      - unzip
      - psmisc

- name: Make sure the /opt directory exists
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install required python packages # Required for grabbing files from sites hosted with SNI
  pip:
    name: '{{ packages }}'
    state: present
    executable: /usr/bin/pip # Force python2.7
  vars:
    packages:
      - urllib3
      - pyopenssl
      - ndg-httpsclient
      - pyasn1
