---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage prerequisites for configuring a base Ubuntu system

- name: Refresh apt cache
  apt:
    update_cache: yes

- name: Remove unused packages
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - landscape-client-ui
      - landscape-client-ui-install
      - landscape-client
      - landscape-common
      - update-motd
      - cloud-init
      - systemd-timesyncd

- name: Add the usual packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bmon
      - htop
      - vim
      - curl
      - gnupg2
      - atop
      - git
      - molly-guard
      - python3-pip
      - python3-dev
      - unzip
      - psmisc
      - net-tools
      - zsh
      - locate

- name: Add packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fzf
      - ripgrep

- name: Make sure the /opt directory exists
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: 0755
