---
#
# Project:: Ansible Role - ubuntu-base
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in ubuntu-base

# Handlers
- name: ubuntu reconfigure timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
